#!/usr/bin/env python3
"""Evaluate predicted query bboxes against GT target boxes.

Inputs:
- Pred bbox JSON generated by process_preprocessed_queries_bbox.py
- nr3d_top10.csv (for query_id -> scan_id + target_id mapping)
- scenes_train_val_info.pkl (for GT aligned bbox per object)

Output:
- Evaluation JSON with per-query IoU and aggregate metrics
- Printed top-k best queries by IoU
"""

from __future__ import annotations

import argparse
import csv
import json
import pickle
from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass
class EvalRecord:
    query_id: str
    scene_id: str
    target_id: int
    status: str
    iou_3d: float
    pred_bbox: list[float] | None
    gt_bbox: list[float] | None
    message: str | None

    def to_json_dict(self) -> dict:
        return {
            "query_id": self.query_id,
            "scene_id": self.scene_id,
            "target_id": self.target_id,
            "status": self.status,
            "iou_3d": self.iou_3d,
            "pred_bbox": self.pred_bbox,
            "gt_bbox": self.gt_bbox,
            "message": self.message,
        }


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Evaluate preprocessed bbox results.")
    parser.add_argument(
        "--pred-json",
        type=Path,
        default=script_dir / "scannet_top10_triangulation_openai_bbox.json",
        help="Prediction JSON from bbox generation script.",
    )
    parser.add_argument(
        "--nr3d-csv",
        type=Path,
        default=script_dir.parent.parent.parent / "data" / "nr3d_top10.csv",
        help="CSV with assignmentid, scan_id, target_id.",
    )
    parser.add_argument(
        "--scene-infos-pkl",
        type=Path,
        default=script_dir
        / "scannet_top10_instance_data"
        / "scenes_train_val_info.pkl",
        help="Scene info pkl containing GT aligned_bbox.",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=script_dir / "scannet_top10_triangulation_openai_bbox_eval.json",
        help="Where to save evaluation JSON.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=10,
        help="Top-k queries to print by IoU.",
    )
    return parser.parse_args()


def load_pred_results(path: Path) -> dict[str, dict]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    results = data.get("results", [])
    return {str(r["query_id"]): r for r in results}


def load_query_metadata(csv_path: Path) -> dict[str, tuple[str, int]]:
    mapping: dict[str, tuple[str, int]] = {}
    with csv_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            qid = (row.get("assignmentid") or "").strip()
            sid = (row.get("scan_id") or "").strip()
            tid = (row.get("target_id") or "").strip()
            if not qid or not sid or not tid:
                continue
            mapping[qid] = (sid, int(tid))
    return mapping


def load_scene_infos(path: Path) -> dict:
    with path.open("rb") as f:
        return pickle.load(f)


def center_size_to_minmax(box6: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    c = box6[:3]
    d = box6[3:6]
    half = d / 2.0
    return c - half, c + half


def iou_aabb_3d(box_a: np.ndarray, box_b: np.ndarray) -> float:
    a_min, a_max = center_size_to_minmax(box_a)
    b_min, b_max = center_size_to_minmax(box_b)

    inter_min = np.maximum(a_min, b_min)
    inter_max = np.minimum(a_max, b_max)
    inter_size = np.maximum(0.0, inter_max - inter_min)
    inter_vol = float(np.prod(inter_size))

    vol_a = float(np.prod(np.maximum(0.0, a_max - a_min)))
    vol_b = float(np.prod(np.maximum(0.0, b_max - b_min)))
    union = vol_a + vol_b - inter_vol
    if union <= 0:
        return 0.0
    return inter_vol / union


def main() -> None:
    args = parse_args()
    if not args.pred_json.is_file():
        raise FileNotFoundError(f"Prediction JSON not found: {args.pred_json}")
    if not args.nr3d_csv.is_file():
        raise FileNotFoundError(f"NR3D CSV not found: {args.nr3d_csv}")
    if not args.scene_infos_pkl.is_file():
        raise FileNotFoundError(f"Scene infos pkl not found: {args.scene_infos_pkl}")

    pred_by_qid = load_pred_results(args.pred_json)
    meta_by_qid = load_query_metadata(args.nr3d_csv)
    scene_infos = load_scene_infos(args.scene_infos_pkl)

    eval_records: list[EvalRecord] = []
    for qid, (scene_id, target_id) in meta_by_qid.items():
        pred = pred_by_qid.get(qid)
        if pred is None:
            eval_records.append(
                EvalRecord(
                    query_id=qid,
                    scene_id=scene_id,
                    target_id=target_id,
                    status="missing_pred",
                    iou_3d=0.0,
                    pred_bbox=None,
                    gt_bbox=None,
                    message="No prediction found for query id.",
                )
            )
            continue

        gt = scene_infos.get(scene_id, {}).get(target_id, {}).get("aligned_bbox")
        if gt is None:
            eval_records.append(
                EvalRecord(
                    query_id=qid,
                    scene_id=scene_id,
                    target_id=target_id,
                    status="missing_gt",
                    iou_3d=0.0,
                    pred_bbox=pred.get("bbox"),
                    gt_bbox=None,
                    message="No GT bbox found for scene/target_id.",
                )
            )
            continue

        gt6 = np.asarray(gt, dtype=np.float64)[:6]
        pred_box = pred.get("bbox")
        if pred_box is None:
            eval_records.append(
                EvalRecord(
                    query_id=qid,
                    scene_id=scene_id,
                    target_id=target_id,
                    status=pred.get("status", "empty"),
                    iou_3d=0.0,
                    pred_bbox=None,
                    gt_bbox=[float(x) for x in gt6.tolist()],
                    message=pred.get("message"),
                )
            )
            continue

        pred6 = np.asarray(pred_box, dtype=np.float64)[:6]
        iou = iou_aabb_3d(pred6, gt6)
        eval_records.append(
            EvalRecord(
                query_id=qid,
                scene_id=scene_id,
                target_id=target_id,
                status=pred.get("status", "ok"),
                iou_3d=float(iou),
                pred_bbox=[float(x) for x in pred6.tolist()],
                gt_bbox=[float(x) for x in gt6.tolist()],
                message=pred.get("message"),
            )
        )

    valid = [r for r in eval_records if r.pred_bbox is not None and r.gt_bbox is not None]
    mean_iou = float(np.mean([r.iou_3d for r in valid])) if valid else 0.0
    acc_025 = float(np.mean([r.iou_3d >= 0.25 for r in valid])) if valid else 0.0
    acc_050 = float(np.mean([r.iou_3d >= 0.50 for r in valid])) if valid else 0.0

    ranked = sorted(valid, key=lambda r: r.iou_3d, reverse=True)
    top_k = ranked[: max(1, args.top_k)]

    output = {
        "summary": {
            "num_queries_csv": len(meta_by_qid),
            "num_predictions_found": sum(1 for r in eval_records if r.status != "missing_pred"),
            "num_valid_for_iou": len(valid),
            "mean_iou": mean_iou,
            "acc_iou_0.25": acc_025,
            "acc_iou_0.50": acc_050,
            "top_k": args.top_k,
        },
        "top_queries": [
            {
                "rank": i + 1,
                "query_id": r.query_id,
                "scene_id": r.scene_id,
                "target_id": r.target_id,
                "iou_3d": r.iou_3d,
                "status": r.status,
            }
            for i, r in enumerate(top_k)
        ],
        "records": [r.to_json_dict() for r in eval_records],
    }

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    with args.output_json.open("w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)

    print(f"Saved evaluation to {args.output_json}")
    print(
        f"Summary: valid={len(valid)}/{len(meta_by_qid)}, "
        f"mean_iou={mean_iou:.4f}, acc@0.25={acc_025:.4f}, acc@0.50={acc_050:.4f}"
    )
    print("Top queries by IoU:")
    for i, r in enumerate(top_k, start=1):
        print(
            f"{i:02d}. query={r.query_id} scene={r.scene_id} target={r.target_id} "
            f"iou={r.iou_3d:.4f}"
        )


if __name__ == "__main__":
    main()
